<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="$(RootNamespace).UnitTests"/>
    <InternalsVisibleTo Include="$(RootNamespace).IntegrationTests"/>
    <InternalsVisibleTo Include="$(RootNamespace).Benchmark"/>
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2"/>
  </ItemGroup>
</Project>
