<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>Yautbox.Mssql</Title>
    <PackageTags>outbox yautbox mssql sqlserver</PackageTags>
    <Description>SQL Server provider for Yautbox with schema migrations and distributed locks for sequential execution.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/maximiliysiss/yautbox/tree/master/src/Yautbox.Mssql</PackageProjectUrl>
    <RepositoryUrl>https://github.com/maximiliysiss/yautbox/tree/master/src/Yautbox.Mssql</RepositoryUrl>
    <PackageId>Yautbox.Mssql</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yautbox\Yautbox.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DistributedLock.SqlServer" />
    <PackageReference Include="FluentMigrator.Runner"/>
    <PackageReference Include="Microsoft.Data.SqlClient"/>
  </ItemGroup>

</Project>
