<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Yautbox\Yautbox.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DistributedLock.SqlServer" />
    <PackageReference Include="FluentMigrator.Runner"/>
    <PackageReference Include="Microsoft.Data.SqlClient"/>
  </ItemGroup>

</Project>
