<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Yautbox\Yautbox.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentMigrator" />
    </ItemGroup>

</Project>
